server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /hanaMbr

---
springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 3600
    re-expiration: 86400
  password:
    encoder:
      iteration: 33
      keylength: 256
---
webclient:
  h2-console-port: 8090
---  
spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          #kakao:
          #  client-secret: ENC(uE4DHfcXtmg/dz9uGueQ/afcj065S2rPcpug1f2rBfdw8VyfNczSaGR/rVsNv5OA)
          google:
            client-id: ENC(rSK4nQrWzg35461UuWFRPO0WF/g45LPIu8Ls8cwNE+7i2PR7Kg3TV4Sn/TuUWoDRLpwUyJJqzfbXxVCdOAkQm+GJoJvNR/WKWanr2DfRKAzjdROpN6eeDQ==)
            client-secret: ENC(4sY1a5YjTVvJyJf7HSzNUEAn+dQlx1zomqOUcq+gRhgk/dGQz/Seys7pC60YwPHW)
            scope: profile, email
     
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

debug: true