server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: ENC(uE4DHfcXtmg/dz9uGueQ/afcj065S2rPcpug1f2rBfdw8VyfNczSaGR/rVsNv5OA)
          google:
            client-id: ENC(rSK4nQrWzg35461UuWFRPO0WF/g45LPIu8Ls8cwNE+7i2PR7Kg3TV4Sn/TuUWoDRLpwUyJJqzfbXxVCdOAkQm+GJoJvNR/WKWanr2DfRKAzjdROpN6eeDQ==)
            client-secret: ENC(4sY1a5YjTVvJyJf7HSzNUEAn+dQlx1zomqOUcq+gRhgk/dGQz/Seys7pC60YwPHW)
            scope: profile, email