DROP TABLE IF EXISTS TB_HANA_MBR;
DROP TABLE IF EXISTS TB_HANA_AUTHORITIES;

CREATE TABLE TB_HANA_MBR (
	MBR_ID		 BIGINT AUTO_INCREMENT PRIMARY KEY,
	MBR_NAME VARCHAR(50) NOT NULL,
	MBR_PASSWORD VARCHAR(200) NOT NULL,
	ENABLED BOOLEAN NOT NULL
);

CREATE TABLE TB_HANA_AUTHORITIES (
    MBR_ID BIGINT NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT FK_AUTHIRITIES_IDS FOREIGN KEY(MBR_ID) REFERENCES TB_HANA_MBR(MBR_ID)
);

CREATE UNIQUE INDEX IX_AUTH_ID ON TB_HANA_AUTHORITIES (MBR_ID,AUTHORITY);