DROP TABLE IF EXISTS TB_HANA_MBR;
DROP TABLE IF EXISTS TB_HANA_INTEREST;
DROP TABLE IF EXISTS TB_HANA_AUTHORITIES;

CREATE TABLE TB_HANA_MBR (
	MBR_ID		  BIGINT AUTO_INCREMENT PRIMARY KEY,
	USER_ID		  VARCHAR(50) NOT NULL,
	USER_NAME	  VARCHAR(50) NOT NULL,
	USER_PASSWORD VARCHAR(200) NOT NULL,
	PHONENUMBER	  VARCHAR(50) NOT NULL,
	NICKNAME	  VARCHAR(50) NOT NULL,
	AGE_RANGE	  VARCHAR(50) NOT NULL,
	REFRESH_TOKEN VARCHAR(200),
	ENABLED		  BOOLEAN NOT NULL
);

CREATE TABLE TB_HANA_AUTHORITIES (
	AUTH_ID	  BIGINT AUTO_INCREMENT PRIMARY KEY,
    MBR_ID	  BIGINT NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT FK_AUTHIRITIES_IDS FOREIGN KEY(MBR_ID) REFERENCES TB_HANA_MBR(MBR_ID)
);

CREATE TABLE TB_HANA_INTEREST (
	INTEREST_ID	BIGINT AUTO_INCREMENT PRIMARY KEY,
    MBR_ID	    BIGINT NOT NULL,
    INTEREST	VARCHAR(50) NOT NULL,
    CONSTRAINT  FK_INTEREST_IDS FOREIGN KEY(MBR_ID) REFERENCES TB_HANA_MBR(MBR_ID)
);

CREATE UNIQUE INDEX IX_AUTH_MBR_ID ON TB_HANA_AUTHORITIES (MBR_ID,AUTHORITY);
CREATE UNIQUE INDEX IX_INTR_MBR_ID ON TB_HANA_INTEREST (MBR_ID,INTEREST);